version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/requirements"
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
      - "dependencies"
    groups:
      dependencies:
          patterns:
            - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
       actions:
          patterns:
            - "*"
