line-length = 88

[lint]
select = [
    "E",    # pycodestyle, see https://beta.ruff.rs/docs/rules/#pycodestyle-e-w
    "D",    # pydocstyle, see https://beta.ruff.rs/docs/rules/#pydocstyle-d
    "F",    # pyflakes, see https://beta.ruff.rs/docs/rules/#pyflakes-f
    "I",    # isort, see https://beta.ruff.rs/docs/rules/#isort-i
    "N",    # pep8-naming, see https://beta.ruff.rs/docs/rules/#pep8-naming-n
    "PTH",  # flake8-use-pathlib, https://beta.ruff.rs/docs/rules/#flake8-use-pathlib-pth
    "TD",   # flake8-todos, https://docs.astral.sh/ruff/rules/#flake8-todos-td
]
ignore = [
#   "E501",  # Line too long. Ignoring this so "ruff.formatter" manages line length.
    "D212", # Multi-line docstring summary should start at the first line
    "TD002", # Missing author in TODOs comment
]

[format]
quote-style = "double"
indent-style = "tab"

[lint.isort]
combine-as-imports = true
force-sort-within-sections = true
known-first-party = ["ansys"]

[lint.pydocstyle]
# Settings: https://docs.astral.sh/ruff/settings/#lintpydocstyle
convention = "numpy"
