# ruff: noqa
# generated by Ansys SCADE Python Wrapper (2.2.2)

import ctypes
from pathlib import Path

# load the SCADE executable code
_lib = ctypes.cdll.LoadLibrary(str(Path(__file__).with_suffix("")))


def make_value(value, type_: type):
    """Return a ctypes value from a Python literal."""
    return type_(*value) if isinstance(value, tuple) else value


# C structures
class _CinC_LowPassRC(ctypes.Structure):
    _fields_ = [("x", ctypes.c_float), ("alpha", ctypes.c_float)]


class LowPassRC:
    def __init__(self, cosim: bool = True):
        self._in_c = _CinC_LowPassRC()
        alloc_fct = _lib.py_alloc_LowPassRC
        alloc_fct.argtypes = []
        alloc_fct.restype = ctypes.c_void_p
        context = alloc_fct()
        self._out_c = ctypes.c_void_p.from_address(context)
        offsets = (ctypes.c_int64 * 1).in_dll(_lib, "py_offsets_LowPassRC")
        self.reset_fct = _lib.LowPassRC_reset
        self.reset_fct.restype = ctypes.c_void_p
        self.cycle_fct = _lib.LowPassRC
        self.cycle_fct.argtypes = [
            ctypes.POINTER(_CinC_LowPassRC),
            ctypes.POINTER(ctypes.c_void_p),
        ]
        self.cycle_fct.restype = ctypes.c_void_p
        self._y = ctypes.c_float.from_address(context + offsets[0])

    def __del__(self):
        free_fct = _lib.py_free_LowPassRC
        free_fct.argtypes = [ctypes.c_void_p]
        free_fct.restype = None
        free_fct(ctypes.byref(self._out_c))

    def call_reset(self) -> None:
        self.reset_fct(ctypes.byref(self._out_c))

    def call_cycle(
        self, cycles: int = 1, refresh: bool = True, debug: bool = False
    ) -> None:
        for i in range(cycles):
            self.cycle_fct(
                self._in_c,
                self._out_c,
            )

    @property
    def x(self) -> float:
        return self._in_c.x

    @x.setter
    def x(self, value: float) -> None:
        self._in_c.x = value

    @property
    def alpha(self) -> float:
        return self._in_c.alpha

    @alpha.setter
    def alpha(self, value: float) -> None:
        self._in_c.alpha = value

    @property
    def y(self) -> float:
        return self._y.value


# end of file
