"""Draw a dashboard from files generated by the SCADE ARINC 661 CDS server."""

import argparse
import csv
from pathlib import Path
import re

import matplotlib.pyplot as plt


def argument_parser():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        prog=f"python {Path(__file__).name}",
        description="This script plots charts based on \
            ARINC 661 performance monitoring data files.",
    )
    parser.add_argument(
        "-l",
        "--server_logs",
        type=str,
        required=True,
        help="path to ARINC 661 server log file, generated with \
            the -mon_profiling and -mon_fps server arguments",
    )
    parser.add_argument(
        "-m",
        "--malloc_csv",
        type=str,
        required=True,
        help="path to memory allocation CSV file, generated with \
            the -mon_memory server arguments",
    )
    parser.add_argument(
        "-n",
        "--network_csv",
        type=str,
        required=True,
        help="path to network traffic CSV file, generated with \
            the -mon_network server arguments",
    )
    return parser


def parse_memory_allocations(malloc_csv_path):
    """Convert a CSV file generated with `-mon_malloc` into a data structure."""
    allocations = {}
    with Path(malloc_csv_path).open(newline="") as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            filename = Path(row["File"]).name
            line, size = row["Line"], int(row["Size (bytes)"])
            key = f"{filename}:{line}"
            if key not in allocations:
                allocations[key] = 0
            allocations[key] += size
    return allocations


def parse_network_traffic(network_csv_path):
    """Convert a CSV file generated with `-mon_network` into a data structure."""
    data = {}
    with Path(network_csv_path).open(newline="") as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            cycle_nb = int(row["CYCLE_NB"])
            ua_id = f"UA_{row['UA_ID']}"
            direction = "RX" if row["Direction"] == "Receive" else "TX"
            size = int(row["Size (bytes)"])
            if cycle_nb not in data:
                data[cycle_nb] = {}
            if ua_id not in data[cycle_nb]:
                data[cycle_nb][ua_id] = {"RX": 0, "TX": 0}
            data[cycle_nb][ua_id][direction] += size
    return [(cycle, dict(ua_data)) for cycle, ua_data in sorted(data.items())]


def parse_exec_times(server_log_path):
    """Convert a `-mon_profiling` & `-mon_fps` log file into a data structure."""
    exec_times = {
        "frame_time": [],
        "fps": [],
        "main_loop": {"avg": [], "min": [], "max": []},
        "network_rx": {"avg": [], "min": [], "max": []},
        "network_tx": {"avg": [], "min": [], "max": []},
        "behavior": {"avg": [], "min": [], "max": []},
        "cpu_draw": {"avg": [], "min": [], "max": []},
        "gpu_draw": {"avg": [], "min": [], "max": []},
    }
    # ruff: noqa: E501
    re_frame = re.compile(r"ms:\s*([\d.]+)\s*FPS:\s*([\d.]+)")
    re_loop = re.compile(
        r"Main loop time \(ms\):\s*([\d.]+)\s*ms,\s*min:\s*([\d.]+),\s*max:\s*([\d.]+)"
    )
    re_net_rx = re.compile(
        r"Network rec\. time \(ms\):\s*([\d.]+)\s*ms,\s*min:\s*([\d.]+),\s*max:\s*([\d.]+)"
    )
    re_net_tx = re.compile(
        r"Network send time \(ms\):\s*([\d.]+)\s*ms,\s*min:\s*([\d.]+),\s*max:\s*([\d.]+)"
    )
    re_behavior = re.compile(
        r"Behavior time \(ms\):\s*([\d.]+)\s*ms,\s*min:\s*([\d.]+),\s*max:\s*([\d.]+)"
    )
    re_cpu = re.compile(
        r"CPU drawing time \(ms\):\s*([\d.]+)\s*ms,\s*min:\s*([\d.]+),\s*max:\s*([\d.]+)"
    )
    re_gpu = re.compile(
        r"GPU drawing time \(ms\):\s*([\d.]+)\s*ms,\s*min:\s*([\d.]+),\s*max:\s*([\d.]+)"
    )

    with Path(server_log_path).open("r") as f:
        for line in f:
            if m := re_frame.search(line):
                exec_times["frame_time"].append(float(m.group(1)))
                exec_times["fps"].append(float(m.group(2)))
            elif m := re_loop.search(line):
                exec_times["main_loop"]["avg"].append(float(m.group(1)))
                exec_times["main_loop"]["min"].append(float(m.group(2)))
                exec_times["main_loop"]["max"].append(float(m.group(3)))
            elif m := re_net_rx.search(line):
                exec_times["network_rx"]["avg"].append(float(m.group(1)))
                exec_times["network_rx"]["min"].append(float(m.group(2)))
                exec_times["network_rx"]["max"].append(float(m.group(3)))
            elif m := re_net_tx.search(line):
                exec_times["network_tx"]["avg"].append(float(m.group(1)))
                exec_times["network_tx"]["min"].append(float(m.group(2)))
                exec_times["network_tx"]["max"].append(float(m.group(3)))
            elif m := re_behavior.search(line):
                exec_times["behavior"]["avg"].append(float(m.group(1)))
                exec_times["behavior"]["min"].append(float(m.group(2)))
                exec_times["behavior"]["max"].append(float(m.group(3)))
            elif m := re_cpu.search(line):
                exec_times["cpu_draw"]["avg"].append(float(m.group(1)))
                exec_times["cpu_draw"]["min"].append(float(m.group(2)))
                exec_times["cpu_draw"]["max"].append(float(m.group(3)))
            elif m := re_gpu.search(line):
                exec_times["gpu_draw"]["avg"].append(float(m.group(1)))
                exec_times["gpu_draw"]["min"].append(float(m.group(2)))
                exec_times["gpu_draw"]["max"].append(float(m.group(3)))
            # else: ignore unrelated lines
    return exec_times


def plot_exec_times(axs, exec_times):
    """Draws four plots from `-mon_fps`/`-mon_profiling` data."""
    groups = [
        ("Main Loop & Behavior", ["main_loop", "behavior"]),
        ("Network RX/TX", ["network_rx", "network_tx"]),
        ("CPU & GPU Draw", ["cpu_draw", "gpu_draw"]),
    ]

    # FPS subplot
    fps = exec_times.get("fps", [])
    ax_fps = axs[0]  # top subplot
    ax_fps.set_xticklabels([])
    if fps:
        x = list(range(len(fps)))
        ax_fps.plot(x, fps, label="FPS", color="tab:green", linewidth=1.8)
        ax_fps.tick_params(axis="x", which="both", bottom=False)
        ax_fps.set_title("Frames Per Second (FPS)")
        ax_fps.set_ylabel("FPS")
        ax_fps.grid(True, linestyle="--", alpha=0.4)
        ax_fps.legend()

    # Grouped metrics (avg with min:max as background)
    for ax, (title, metrics) in zip(axs[1:], groups):
        for name in metrics:
            metric = exec_times.get(name)
            if not metric or not metric["avg"]:
                continue

            ax.set_xticklabels([])
            ax.tick_params(axis="x", which="both", bottom=False)

            x = list(range(len(metric["avg"])))
            avg, min_v, max_v = metric["avg"], metric["min"], metric["max"]

            ax.plot(x, avg, label=f"{name} avg", linewidth=1.8)
            ax.fill_between(x, min_v, max_v, alpha=0.2)

        ax.set_title(title)
        ax.set_ylabel("Time (ms)")
        ax.grid(True, linestyle="--", alpha=0.4)
        ax.legend()


def plot_memory_allocations(axs, allocation_data, max_items=15):
    """Draw a pie chart from `-mon_malloc` data."""
    # Split between top items and an "other" category
    sorted_items = sorted(allocation_data.items(), key=lambda x: x[1], reverse=True)
    top_items, other_items = sorted_items[:max_items], sorted_items[max_items:]
    other_total = sum(v for _, v in other_items)
    labels, sizes = [k for k, _ in top_items], [v for _, v in top_items]
    if other_total > 0:
        labels.append("Other")
        sizes.append(other_total)
    total = sum(sizes)

    wedges, _, _ = axs[0].pie(
        sizes, autopct=lambda p: f"{p:.1f}%" if p > 1 else "", startangle=140
    )
    axs[0].set_title("Definition Phase Memory Allocation")

    legend_labels = [
        f"{label} — {size:,} B ({size / total * 100:.1f}%)".replace(",", " ")
        for label, size in zip(labels, sizes)
    ]

    axs[1].legend(
        wedges,
        legend_labels,
        title="Top allocations",
        loc="center",
    )
    axs[1].axis("off")


def plot_network_traffic(ax, network_data):
    """Draw a chart from `-mon_network` data."""
    # Collect all UA IDs
    ua_ids = set()
    for _, ua_data in network_data:
        ua_ids.update(ua_data.keys())
    ua_ids = sorted(ua_ids)

    # Plot each UA's RX/TX
    for ua in ua_ids:
        cycles = []
        rx_values = []
        tx_values = []
        for cycle, ua_data in network_data:
            cycles.append(cycle)
            rx_values.append(ua_data.get(ua, {}).get("RX", 0))
            tx_values.append(ua_data.get(ua, {}).get("TX", 0))

        ax.plot(cycles, rx_values, label=f"{ua} RX")
        ax.plot(cycles, tx_values, linestyle="--", label=f"{ua} TX")

    ax.set_xlabel("Cycle Number")
    ax.set_ylabel("Bytes")
    ax.set_title("UA Traffic per Cycle")
    ax.grid(True)
    ax.legend(fontsize=8)


def plot_combined(exec_times, allocation_data, network_data):
    """Combine all charts into one window."""
    fig = plt.figure(figsize=(18, 12))
    gs = fig.add_gridspec(4, 4, width_ratios=[1, 1, 1, 1], height_ratios=[1, 1, 1, 1])

    # Left: 4 stacked metric plots
    axs_metrics = [fig.add_subplot(gs[i, 0:2]) for i in range(4)]
    plot_exec_times(axs_metrics, exec_times)

    # Right top: memory pie
    axs_pie = [fig.add_subplot(gs[0:2, 2]), fig.add_subplot(gs[0:2, 3])]
    plot_memory_allocations(axs_pie, allocation_data)

    # Right bottom: UA traffic
    ax_ua = fig.add_subplot(gs[2:, 2:])
    plot_network_traffic(ax_ua, network_data)

    fig.suptitle("ARINC 661 CDS server performance", fontsize=16)
    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    args = argument_parser().parse_args()
    exec_times = parse_exec_times(args.server_logs)
    malloc = parse_memory_allocations(args.malloc_csv)
    network = parse_network_traffic(args.network_csv)

    plot_combined(exec_times, malloc, network)
